name: Tapyrus Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tapyrus:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-15]
        architecture: [x64_64, arm64]  # Added architecture matrix
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Dependencies
        run: |
          if [[ $RUNNER_OS == "Linux" ]]; then
            if [[ ${{ matrix.architecture }} == "x64_64" ]]; then
              sudo apt-get update -y
              sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl
            elif [[ ${{ matrix.architecture }} == "arm64" ]]; then
              sudo apt-get update -y
              sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl gcc-aarch64-linux-gnu
            fi
          elif [[ $RUNNER_OS == "macOS" ]]; then
            brew update
            brew install automake libtool pkg-config
          fi

      - name: Call reusable workflow for building Tapyrus Core
        uses: ./.github/workflows/reusable_tapyrus_workflow.yml
        with:
          build_env: ${{ matrix.architecture }}  # Pass architecture as a string
          build_config: |
            --enable-debug
            --with-gui=no
            --disable-wallet
          os_packages: |
            if [[ $RUNNER_OS == "Linux" ]]; then
              if [[ ${{ matrix.architecture }} == "x64_64" ]]; then
                sudo apt-get update -y
                sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl
              elif [[ ${{ matrix.architecture }} == "arm64" ]]; then
                sudo apt-get update -y
                sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl gcc-aarch64-linux-gnu
              fi
            elif [[ $RUNNER_OS == "macOS" ]]; then
              brew update
              brew install automake libtool pkg-config
            fi
          depends_build: |
            if [[ ${{ matrix.architecture }} == "x64_64" ]]; then
              make -C depends -j$(nproc) NO_QT=1
            elif [[ ${{ matrix.architecture }} == "arm64" ]]; then
              make -C depends -j$(nproc) NO_QT=1 ARCH=arm64
            fi
